### ISSUE TITLE
Files do not exist

### ISSUE THREAD

**Issue by AwolDes** [TVke/react-native-tailwindcss#12]
Hey there

Just installed `v1.1.8` in a new react native project and have gotten the following error when running `react0native start`

```bash
error: bundling failed: Error: Unable to resolve module `../stubs/simpleConfig.stub` from `node_modules/react-native-tailwindcss/util/configHandler.js`: 

None of these files exist:
  * node_modules/react-native-tailwindcss/stubs/simpleConfig.stub(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-native-tailwindcss/stubs/simpleConfig.stub/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
```

This is what the package looks like in `node_modules`
![image](https://user-images.githubusercontent.com/9693812/72197480-75c2c600-346d-11ea-90c9-7ee33fb60f93.png)

So it looks like the reference to the `stubs` directory would throw a missing file error because that directory does not exist.

I am on Ubuntu 18.04, and tried to both npm and yarn install the package with no luck. I also tried to install `v1.1.7` of this package and was met with a similar result.

`react` version: `16.9.0`
`react-native` version: `0.61.5`

Any help would be appreciated! Cheers

**Comment by TVke** [comment]
Hi @AwolDes 

Sorry for that mistake on my part 
After updating to `1.1.9` there should be no more problem
Thank you for noticing this bug

greetings
@TVke

**Comment by AwolDes** [comment]
Thanks for looking into this!
