### ISSUE TITLE
[Documentation] Invalid link and package name

### ISSUE THREAD

**Issue by Zapominacz** [TVke/react-native-tailwindcss#15]
Hi! I have found two issues related to first page of docs:

**First**:
There is a difference between:
https://github.com/TVke/react-native-tailwindcss/blob/master/README.md
(install react-native-tailwindcss)
and
https://github.com/TVke/react-native-tailwindcss/blob/master/docs/installation.md
(install tailwindcss)

I assume the first one is correct. Can add PR for that if my assumptions are true

**Second**:
In: 
https://github.com/TVke/react-native-tailwindcss/blob/master/docs/installation.md

Last link: https://tvke.github.io/react-native-tailwindcss/customiation/configuration
should be changed to https://tvke.github.io/react-native-tailwindcss/customization/configuration

Just a typo, can be changed with the first issue

**Comment by TVke** [comment]
Hi @Zapominacz

A PR would be great 😃 
Thank you for the careful reading

greetings
@TVke

**Comment by Zapominacz** [comment]
Added PR #17
