### ISSUE TITLE
Failed running npx RNtailwindcss (no such file)

### ISSUE THREAD

**Issue by jankeesvw** [TVke/react-native-tailwindcss#19]
I am trying out react-native-tailwindcss and I ran into an issue setting it up:

```
$ npx RNtailwindcss
cp: ../react-native-tailwindcss/stubs/defaultConfig.stub.js: No such file or directory
```

**Comment by karlerikjonatan** [comment]
I ran into the same problem earlier today. What I discovered is that the documentation in `master` is outdated. What you want to run is:

```shell
npx tailwind init
```

And [here's the branch with the correct documentation](https://github.com/TVke/react-native-tailwindcss/tree/fix/default-config-not-found#usage).

**Comment by TVke** [comment]
Hi @jankeesvw 

Could you please provide me the version of `react-native-tailwindcss` as this works only in the latest version

Greetings
Thomas

**Comment by jankeesvw** [comment]
I am using: 

```
react-native-tailwindcss@^1.1.9:
  version "1.1.9"
```

I managed to fix this by creating the file manually.
