### ISSUE TITLE
Not loading custom tailwind config?

### ISSUE THREAD

**Issue by larsjanssen6** [TVke/react-native-tailwindcss#21]
Hi,

Thanks for this project :) realy cool. It looks like my custom `tailwind.config.js`
is not being used. Currently I have this:

```
module.exports = {
    theme: {
        extend: {
            colors: {
                primary: '#484848',
                second: '#FF5A5F',
                third: '#008489',
                facebook: '#3b5998',
                twitter: '#38A1F3',
            },
        },
    },
};
```

But I can't do this in my project, not working:

```
<View style={[t.bgPrimary, t.h24]}></View>
```

Any idea what I'm doing wrong? I use version `^1.1.9"`.

Thanks!

**Comment by TVke** [comment]
Hi @larsjanssen6 

I have no idea what the problem could be. have you tried a fresh install of react-native?

greetings
Thomas

**Comment by ReneMoraales** [comment]
@larsjanssen6 Did you figure it out?

**Comment by TVke** [comment]
Hi @ReneMoraales 

I didn't figure out what the problem was as I can not recreate it. 
I have passing tests so if you have a failing test case for me or a project I can examine, I will try to debug this but for now I can not do more then this.

greetings
Thomas

**Comment by larsjanssen6** [comment]
@ReneMoraales I never found a solution :( Sorry.

**Comment by TVke** [comment]
@ReneMoraales 
can you send me a repo with your setup? so I can test it?

**Comment by dembeEdward** [comment]
Hi

I really love this module and I faced the same issue. 

In my case rebuilding the project after updating the config file helped. Hope this will save someone some time. Also, this should be documented as default expectation, after running `npx tailwind init`, is that the styles will be applied immediately after updating the newly created file.

**Comment by TVke** [comment]
This is a good idea 

I would accept a PR for this

**Comment by dembeEdward** [comment]
> This is a good idea
> 
> I would accept a PR for this

https://github.com/TVke/react-native-tailwindcss/pull/60
