### ISSUE TITLE
cannot generate tailwind config file 

### ISSUE THREAD

**Issue by jassehomar** [TVke/react-native-tailwindcss#30]
Hi everyone. I ran into an error of generating the tailwind.config file. Here is the command below and output:

```bash
npx RNtailwindcss
cp: cannot stat '../react-native-tailwindcss/stubs/defaultConfig.stub.js': No such file or directory
```

**Comment by thomas-j-back** [comment]
I just came here to post about the same issue. Attempting to run the` npx RNtailwindcss `returns
the same output for me.

**Comment by thomas-j-back** [comment]
> Hi everyone. I ran into an error of generating the tailwind.config file. Here is the command below and output:
> 
> ```shell
> npx RNtailwindcss
> cp: cannot stat '../react-native-tailwindcss/stubs/defaultConfig.stub.js': No such file or directory
> ```

I was able to generate a tailwind.config file by running
`npx tailwind init`

If you check out the README.md included with the repository it includes different options for generating the config file with this command.

**Comment by fredrivett** [comment]
For those looking for a simple solution, you can just copy one of the files from the `stubs` directory in this repo to `tailwind.config.js`: https://github.com/TVke/react-native-tailwindcss/tree/master/stubs
