### ISSUE TITLE
Aspect Ratio & Sizes

### ISSUE THREAD

**Issue by jbrodriguez** [TVke/react-native-tailwindcss#34]
First of all, nice library ! Very easy to use

I wonder what were your thoughts regarding having sizes depend on devices aspect ratio.

react-native-style-tachyons, let's you configure a rem property, which can be set based on screen size, etc (https://github.com/tachyons-css/react-native-style-tachyons#usage).

Additionally, you could expose standalone sizes, which would be aspect ratio based as well.

I'd guess to achieve this, support from the underlying library would be required.

**Comment by TVke** [comment]
Hey @jbrodriguez 

I discarded the screen sizes as media queries are not the same in react native as online.
I personally use the `Dimensions.get('window')` to get the width and height of the device and apply styles accordingly.
For this moment it is not in the plans to implement something like this.
If you do think this is essential I would like to implement and not depend on tachyons as that is a small part of the library we would use.

I would a PR like this with pleasure.

greetings
Thomas

**Comment by jbrodriguez** [comment]
hey @TVke , just to be on the same page, what I meant is having sizes responds to a seed value

for example

t.textBase = 16 * rem
t.textLg = 18 * rem

where rem could be specified in some initial configuration

rem = width/height * 0.75 (or whatever)

**Comment by TVke** [comment]
Hi @jbrodriguez 

I do understand you better now. 
As this would add a lot of complexity to the package, I do’t think this would be a big advantage. 
Now it works as tailwindcss users expect and that is still the main goal. 

Thank you for the suggestion. 

Greetings 
Thomas
