### ISSUE TITLE
How to run react-native-tailwindcss with postcss?

### ISSUE THREAD

**Issue by zendevil** [TVke/react-native-tailwindcss#37]
Sorry, I'm unable to use this library! In my web tailwind projects, I usually run the postcss command on a style file that contains:

```
@tailwind base;

@tailwind components;

@tailwind utilities;
```

set the output directory, and then set the generated file as the href of a style tag in my index.html. How to exactly use react-native-tailwind?

**Comment by TVke** [comment]
Hi @zendevil 

PostCSS is not needed and a styling file is also redundant.
You can just copy and paste your tailwind config file (or generate a new one) and the styles can be used in your code.
If you have any more questions, shoot 😊 
The full installation setup you can find in the docs: https://tvke.github.io/react-native-tailwindcss/installation.html

Greetings
Thomas
