### ISSUE TITLE
tailwind config js doesnt work properly

### ISSUE THREAD

**Issue by infothien** [TVke/react-native-tailwindcss#44]
Hi there, first of all I would like to say it was a very useful and great lib support tailwind for react native. Thank you

I got a small issue and dont know why. I defined my tailwind.config.js like this 
<img width="741" alt="tailwind_config_js_—_dentsu" src="https://user-images.githubusercontent.com/30365498/88792784-c5cd6400-d1d6-11ea-9e53-0ed1241092bd.png">

but it doesnt actually work as my expectation 
<img width="862" alt="Screenshot_2020_07_29_20_05" src="https://user-images.githubusercontent.com/30365498/88792839-dda4e800-d1d6-11ea-9e5c-32db47311ed2.png">

**Expectation:**  only have the bgRed in this case.

My environment:
_ "react": "16.13.1",
_ "react-native": "0.63.2",
_ "react-native-tailwindcss": "^1.1.10"

Wonder did I miss something, hope to get your response soon. Thanks

**Comment by TVke** [comment]
Hi @infothien 

I understand the expected behaviour. 
This is a very hard thing to do and that is why I choose to put only suggestions from the standard config file as possibilities.

Hope this explains it a bit

greetings
Thomas

**Comment by infothien** [comment]
Thank you ! I got it then I will close this one for now maybe  @TVke
