### ISSUE TITLE
Documentation styling appears broken

### ISSUE THREAD

**Issue by rareyman** [TVke/react-native-tailwindcss#45]
When visiting the documentation, the styling looks off. I am wondering if the link to the stylesheet has been severed or some changes have been made to the styling on the main Tailwind documentation site that is affecting this…?

Not super high priority as the documentation is still usable, but it would be nice to have the page look better. 😊

**Comment by TVke** [comment]
Hi @rareyman 

thank you very much for notifying me.
I will fix this immediately.

Greetings
Thomas

**Comment by rareyman** [comment]
Has this been updated…? The documentation still looks broken! 😨

**Comment by TVke** [comment]
Hi @rareyman 

I'm sorry you are correct I will implement a more permanent solution. 

Greetings 
Thomas

**Comment by rareyman** [comment]
No worries at all. I appreciate all the hard work on this project. 🙂

**Comment by TVke** [comment]
Hi @rareyman 

oké I checked now everything should be oké again.
If you notice something again let me know.

Thank you so much.

greetings
Thomas

**Comment by rareyman** [comment]
Looks great! Thanks again for this awesome library!
