### ISSUE TITLE
maxW{Size} not working

### ISSUE THREAD

**Issue by markstreich** [TVke/react-native-tailwindcss#55]
The maxW{Size} does not seem to work (typescript has typings for these, and the docs suggest `t.maxW{Size}` should work):

https://tvke.github.io/react-native-tailwindcss/sizing/max-width.html

```js
console.log(tw.maxW3);
```
```
undefined
```

The named units work though:
```js
console.log(tw.maxWXs);
```
```
Object {
  "maxWidth": 320,
}
```

**Comment by TVke** [comment]
Hi @markstreich 

I think you ment to use `tw.maxW3xl` as there is no option `tw.maxW3` in the docs

greetings
Thomas

**Comment by markstreich** [comment]
@TVke Thanks, there are typescript entries for example for `tw.maxW3` though.

https://github.com/TVke/react-native-tailwindcss/blob/721c3699b1b421bf0e937012f5436a89d62f0004/index.d.ts#L3282

If nothing else, might be an inconsistency in the typescript types?

**Comment by TVke** [comment]
Hi @markstreich 

There are indeed inconsistencies in the typescript definition and theere are 2 PR's working to improve it. 
For now I am going to leave it but if I have the time I will maken an intermediate PR to fix the typescript problems.

greetings
Thomas

**Comment by markstreich** [comment]
Thanks! For my needs it’s not urgent at all, I’m keeping an eye on the pending PRs.
